# General settings.
general:
  # Reward limiter settings.
  reward-limiter:
    # Enabling the reward limiter makes it so that the player can only receive a set amount of rewards within a set time frame.
    enabled: false
    # The player will be allowed to receive only this amount of rewards within the set time frame.
    limit: 10
    # The message the player will receive when they reach the reward limit.
    limit-reached-message: "&cYou have reached the reward limit. You have to wait for a while before you can receive more rewards."
    # The time after which the player will be able to receive rewards again, counting upon the first reward received. The cooldown is expressed in the format ‘10d’, ‘5h’, ‘30m’, ‘20s’, ‘10m30s’, etc.
    cooldown: 10m

# Block related settings and rewardable activities.
block:
  # Ownership check settings.
  ownership-check:
    # Whether break ownership of the block should be checked.
    # If set to true, breaking a block that was placed by a player
    # will result in no rewards given.
    break: true
    # Whether place ownership of the block should be checked.
    # If set to true, placing a block in a place where there was already a block broken by a player
    # will result in no rewards given.
    place: true
  # Block break rewardable activities section.
  # Block break rewardable activities trigger on block break.
  break:
    # Block type.
    stone:
      # Groups with the rewards.
      # There has to be a 'default' group at least.
      # There can also be more groups but the "better" ones should be below the others.
      # For example:
      # default ("the worst" group -> first)
      # vip ("better than the default" group -> below the 'default' group)
      # mvp ("better than the vip" group -> below the 'vip' group)
      # Permission to be able to receive group rewards: 'rewardableactivities.group.<group>'
      # (default group does not require this permission)
      # Default reward group.
      default:
        # Chance to obtain this reward.
        chance: 75.0
        # Economy settings (require Vault and economy plugin to be used).
        # Economy settings can be ommited if ^ conditions are not met.
        # Minimum economy that the player will receive.
        minimum-economy: 0.0
        # Maximum economy that the player will receive.
        maximum-economy: 4.0
        # Commands that will be executed.
        # Available placeholders:
        # {player} -> player name
        commands:
        - "say {player} broke a stone! ({group})"
      # Additional reward group.
      # As you can see below, you can provide more rewards
      # but only one will be chosen (there is a chance for
      # all rewards to fail resulting in no rewards).
      vip:
      - chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 8.0
        commands:
        - "say {player} broke a stone! ({group} 75%)"
      - chance: 25.0
        minimum-economy: 0.0
        maximum-economy: 32.0
        commands:
        - "say {player} broke a stone! ({group} 25%)"
      # Additional reward group.
      mvip:
      - chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 16.0
        commands:
        - "say {player} broke a stone! ({group} 75%)"
      - chance: 25.0
        minimum-economy: 0.0
        maximum-economy: 96.0
        commands:
        - "say {player} broke a stone! ({group} 25%)"
    grass_block:
      default:
        chance: 100.0
        commands:
        - "say {player} broke a grass block! ({group})"
  # Block place rewardable activities section.
  # Block place rewardable activities have the same exact settings as the block break ones.
  # Block place rewardable activities trigger on block place.
  place:
    diamond_block:
      default:
        chance: 100.0
        commands:
        - "say {player} placed a diamond block! ({group})"

# Entity related settings and rewardable activities.
entity:
  # Ownership check settings.
  ownership-check:
    # Whether breed ownership of the entity should be checked.
    # If set to true, killing an entity that was bred by a player
    # will result in no rewards given.
    breed: true
    # Whether spawner ownership of the entity should be checked.
    # If set to true, killing an entity that was spawned by a spawner
    # will result in no rewards given.
    spawner: true
  # Entity kill rewardable activities section.
  # Entity kill rewardable activities trigger on entity kill.
  kill:
    # Entity type.
    zombie:
      # Groups with the rewards.
      # There has to be a 'default' group at least.
      # There can also be more groups but the "better" ones should be below the others.
      # For example:
      # default ("the worst" group -> first)
      # vip ("better than the default" group -> below the 'default' group)
      # mvp ("better than the vip" group -> below the 'vip' group)
      # Permission to be able to receive group rewards: 'rewardableactivities.group.<group>'
      # (default group does not require this permission)
      # Default reward group.
      default:
        # Chance to obtain this reward.
        chance: 75.0
        # Economy settings (require Vault and economy plugin to be used).
        # Economy settings can be ommited if ^ conditions are not met.
        # Minimum economy that the player will receive.
        minimum-economy: 0.0
        # Maximum economy that the player will receive.
        maximum-economy: 4.0
        # Commands that will be executed.
        # Available placeholders:
        # {player} -> player name
        commands:
        - "say {player} killed a zombie! ({group})"
      # Additional reward group.
      vip:
        chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 8.0
        commands:
        - "say {player} killed a zombie! ({group})"
      # Additional reward group.
      mvip:
        chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 16.0
        commands:
        - "say {player} killed a zombie! ({group})"
    pig:
      default:
        chance: 100.0
        commands:
        - "say {player} killed a pig! ({group})"
  # Entity breed rewardable activities section.
  # Entity breed rewardable activities have the same exact settings as the entity kill ones.
  # Entity breed rewardable activities trigger on entity kill.
  breed:
    pig:
      default:
        chance: 100.0
        commands:
        - "say {player} bred a pig! ({group})"

# Item related settings and rewardable activities.
item:
  # Item catch rewardable activities section.
  # Item catch rewardable activities trigger on item fish.
  fish:
    # Material.
    salmon:
      # Groups with the rewards.
      # There has to be a 'default' group at least.
      # There can also be more groups but the "better" ones should be below the others.
      # For example:
      # default ("the worst" group -> first)
      # vip ("better than the default" group -> below the 'default' group)
      # mvp ("better than the vip" group -> below the 'vip' group)
      # Permission to be able to receive group rewards: 'rewardableactivities.group.<group>'
      # (default group does not require this permission)
      # Default reward group.
      default:
        # Chance to obtain this reward.
        chance: 75.0
        # Economy settings (require Vault and economy plugin to be used).
        # Economy settings can be ommited if ^ conditions are not met.
        # Minimum economy that the player will receive.
        minimum-economy: 0.0
        # Maximum economy that the player will receive.
        maximum-economy: 4.0
        # Commands that will be executed.
        # Available placeholders:
        # {player} -> player name
        commands:
        - "say {player} fished a salmon! ({group})"
      # Additional reward group.
      # As you can see below, you can provide more rewards
      # but only one will be chosen (there is a chance for
      # all rewards to fail resulting in no rewards).
      vip:
      - chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 8.0
        commands:
        - "say {player} fished a salmon! ({group} 75%)"
      - chance: 25.0
        minimum-economy: 0.0
        maximum-economy: 32.0
        commands:
        - "say {player} fished a salmon! ({group} 25%)"
      # Additional reward group.
      mvip:
      - chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 16.0
        commands:
        - "say {player} fished a salmon! ({group} 75%)"
      - chance: 25.0
        minimum-economy: 0.0
        maximum-economy: 96.0
        commands:
        - "say {player} fished a salmon! ({group} 25%)"
